<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <!-- Параметры проекта -->
  <groupId>namespace.stedd</groupId>
  <artifactId>data</artifactId>
  <version>1.4</version>
  <packaging>jar</packaging>
  <name>veno</name>
  <description>Библиотека по управлению данными</description>
  <url>https://github.com/namespaceStedd/veno</url>

  <!-- Лицензия -->
  <licenses>
    <license>
      <name>Namespace Stedd</name>
      <url>http://itx19.site</url>
    </license>
  </licenses>

  <!-- Публикация -->
  <distributionManagement>
    <repository>
      <id>veno</id>
      <name>namespaceStedd</name>
      <url>https://maven.pkg.github.com/namespacestedd/veno</url>
    </repository>
  </distributionManagement>

  <!-- Разработчики -->
  <developers>
    <developer>
      <id>namespaceStedd</id>
      <name>Alex ITX PSU</name>
      <email></email>
      <url>http://itx19.site</url>
      <organization>ITX</organization>
      <organizationUrl>http://itx19.site</organizationUrl>
      <roles>
        <role>architect</role>
        <role>developer</role>
      </roles>
      <timezone>Asia/Yekaterinburg</timezone>
      <properties>
        <picUrl></picUrl>
      </properties>
    </developer>
  </developers>

  <!-- Свойства проекта -->
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <java.version>21</java.version>
    <github.global.server>github</github.global.server>
    <github.maven-plugin>0.9</github.maven-plugin>
  </properties>

  <!-- Зависимости проекта -->
  <dependencies>
    <!-- Тесты -->
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
    <!-- JSON -->
    <dependency>
      <groupId>com.google.code.gson</groupId>
      <artifactId>gson</artifactId>
      <version>2.9.1</version>
    </dependency>
    <!-- Журналирование -->
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-core</artifactId>
      <version>2.24.1</version>
    </dependency>
  </dependencies>

  <!-- Сборка проекта -->
  <build>
    <finalName>${project.name}-${project.version}</finalName>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <configuration>
          <source>21</source>
          <target>21</target>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>3.6.2</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <configuration>
              <artifactSet>
                <includes>
                  <include>com.google.code.gson:gson</include>
                </includes>
              </artifactSet>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
